---
title: "Proportions of red beads"
format: html
execute: 
  echo: false
---


```{r}
library(tidyverse)
library(tidymodels)
library(broom)

# Estimating proportions is a common objective in statistics, particularly when working with categorical data. In this case, we explore the proportion of red beads by simulating an urn containing 1,000 beads.
We draw a sample of 50 beads to estimate how many in the urn are red. But if the beads were changed after our sample, our estimate could be wrong.We draw a sample of 50 beads from an urn containing only red and white beads to estimate the proportion that are red. If the contents of the urn change after our sample, our estimate may no longer be accurate. We model each bead's color as a Bernoulli trial with an unknown probability of being red.

```

```{r}
\[
Y = f(X_1, X_2, \ldots, X_k) + \varepsilon
\]

```

```{r}
\[
\hat{Y} = \frac{1}{1 + \exp\left(-(-1.2 + 0.8 \cdot X_1 + 0.05 \cdot X_2)\right)}
\]

```
```{r}
#| cache: true
$$\widehat{\text{logit}(P(\text{color} = \text{red}))} = -0.66$$
```